// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyMQjVopdkl3n1_VWa2N06mQMSgn8a2CI',
    appId: '1:637006406422:web:272454498c530cbe472637',
    messagingSenderId: '637006406422',
    projectId: 'ecommerce-app-b8131',
    authDomain: 'ecommerce-app-b8131.firebaseapp.com',
    storageBucket: 'ecommerce-app-b8131.firebasestorage.app',
    measurementId: 'G-4Y2WDJ10ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNwgnoNfsYsTBx0mdgQOrSbVEgLOkkA4',
    appId: '1:637006406422:android:078ca2bbcb1882db472637',
    messagingSenderId: '637006406422',
    projectId: 'ecommerce-app-b8131',
    storageBucket: 'ecommerce-app-b8131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVHAvVLKm2P481arXTnW17Px2lCSTph6A',
    appId: '1:637006406422:ios:5cf7382609c30408472637',
    messagingSenderId: '637006406422',
    projectId: 'ecommerce-app-b8131',
    storageBucket: 'ecommerce-app-b8131.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
